# This program is designed to have a conversation with the user by
# asking for their name and age, displaying the current date, and predicting
# how old they will be in ten years.

import datetime

# The current date is generated by using the datetime module, which allows
# access the system's current date and time and format it in a readable way.
today = datetime.date.today()

# Ask the user for their name
name = input("What is your name? ")

# Greet the user
print(f"Hello, {name}! It's nice to meet you.")

# Display the current date in a user-friendly format
print(f"Today's date is {today.strftime('%B %d, %Y')}.")

# Ask the user for their age
age = int(input("How old are you? "))

# Calculate the user's age in ten years
future_age = age + 10

# Tell the user how old they will be in ten years
print(f"In ten years, you will be {future_age} years old!")